version: '3.7'

services:
    # Aplicação Laravel
    app:
        container_name: kanastra-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/database/database.sqlite
            - QUEUE_CONNECTION=redis
        command: >
            sh -c "
                composer install &&
                php artisan key:generate &&
                php artisan migrate --force &&
                php-fpm
            "

    # Nginx
    nginx:
        container_name: kanastra-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    # Fila de Processamento
    queue-worker-1:
        container_name: kanastra-queue-worker-1
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work --tries=3"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    queue-worker-2:
        container_name: kanastra-queue-worker-2
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work --tries=3"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # Redis
    redis:
        container_name: kanastra-redis
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
