version: '3.7'

services:
    # Aplicação Laravel
    app:
        container_name: kanastra-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - db
        networks:
            - laravel
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=kanastra
            - DB_USERNAME=postgres
            - DB_PASSWORD=secret
            - QUEUE_CONNECTION=redis

    # Nginx
    nginx:
        container_name: kanastra-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    # Fila de Processamento
    queue-worker-1:
        container_name: kanastra-queue-worker-1
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work --tries=3"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    queue-worker-2:
        container_name: kanastra-queue-worker-2
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work --tries=3"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # Redis
    redis:
        container_name: kanastra-redis
        image: redis:latest
        networks:
            - laravel

    # Banco de Dados PostgreSQL
    db:
        container_name: kanastra-db
        image: postgres:12
        restart: unless-stopped
        environment:
            POSTGRES_DB: kanastra
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - ./.docker/postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
